### ISSUE TITLE
UnhandledPromiseRejectionWarning

### ISSUE THREAD

**Issue by aapiskukko** [lotockii/node-red-contrib-postgres-variable#3]
Hi. Thanks for the great plugin. However, I am constantly getting this kind of log in Node-RED logs. Any idea how could I make this go away?

`(node:7785) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 23)                                                                
(node:7785) UnhandledPromiseRejectionWarning: Error: This socket has been ended by the other party
    at Socket.writeAfterFIN [as write] (net.js:393:12)
    at Connection.end (/usr/lib/node/node-red/node_modules/node-red-contrib-postgres-variable/node_modules/pg/lib/connection.js:318:22)
    at global.Promise (/usr/lib/node/node-red/node_modules/node-red-contrib-postgres-variable/node_modules/pg/lib/client.js:410:23)
    at new Promise (<anonymous>)
    at Client.end (/usr/lib/node/node-red/node_modules/node-red-contrib-postgres-variable/node_modules/pg/lib/client.js:409:12)
    at Pool._remove (/usr/lib/node/node-red/node_modules/node-red-contrib-postgres-variable/node_modules/pg-pool/index.js:142:12)
    at Timeout.setTimeout (/usr/lib/node/node-red/node_modules/node-red-contrib-postgres-variable/node_modules/pg-pool/index.js:298:14)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
`

Version: 0.0.18
Node version: 10.15.3

**Comment by 0xBiriyani** [comment]
Hi
Thanks for your plugin. You did a great job man. I am using it rn but as @aapiskukko mentioned I am facing this error.

**Task:**
I am executing an insert query for every one second to store data in Postgres SQL Server. Then I am getting the same exception in the console log. Please let us know if we can do anything to fix.

** Note:**
There is no issue in the execution of the query other than this log.

Module version : 0.0.18
Node Version : v10.15.2

![pgsql nodered exception](https://user-images.githubusercontent.com/41888820/66799182-b45be980-ef2d-11e9-8da7-cdc0a845784e.png)

**Comment by dmvstar** [comment]
I have the same problem.
(node:141952) UnhandledPromiseRejectionWarning: Error [ERR_STREAM_WRITE_AFTER_END]: write after end
    at writeAfterEnd (_stream_writable.js:248:12)
    at Socket.Writable.write (_stream_writable.js:296:5)
    at Connection.end (C:\Users\dstarzhynskyi\.node-red\node_modules\pg\lib\connection.js:318:22)
    at global.Promise (C:\Users\dstarzhynskyi\.node-red\node_modules\pg\lib\client.js:410:23)
    at new Promise (<anonymous>)
    at Client.end (C:\Users\dstarzhynskyi\.node-red\node_modules\pg\lib\client.js:409:12)
    at Pool._remove (C:\Users\dstarzhynskyi\.node-red\node_modules\pg-pool\index.js:142:12)
    at Timeout.setTimeout (C:\Users\dstarzhynskyi\.node-red\node_modules\pg-pool\index.js:298:14)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
(node:141952) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
